.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MPUB" "8" "November 2017" "" ""
.
.SH "NAME"
\fBmpub\fR \- multicast heartbeat publisher
.
.SH "SYNOPSIS"
\fBmpub\fR \fIOPTIONS\fR \fIiface\fR=\fImaddr\fR [iface=maddr \.\.\.]
.
.SH "DESCRIPTION"
The \fBmpub\fR utility publishes multicast UDP datagrams to a set of network endpoints\. It can be used in conjunction with the \fBmsub(8)\fR utility to test and debug multicast network configurations\.
.
.SH "OPTIONS"
The utility accepts the following command\-line options:
.
.TP
\fB\-b\fR \fIBSZ\fR
Sets the socket send buffer size to \fIBSZ\fR bytes\. If not specified, the value defaults to the Linux kernel default\.
.
.TP
\fB\-c\fR \fICNT\fR
Sets the number of outgoing datagrams per endpoint to \fICNT\fR\. If not specified, the value defaults to 5\.
.
.TP
\fB\-e\fR
The process will terminate when the first publishing error is encountered\. If not specified, the process will only print the relevant error message\.
.
.TP
\fB\-h\fR
Prints the usage message\.
.
.TP
\fB\-i\fR \fIDUR\fR
Sets the interval between outgoing datagrams per endpoint to the specified duration (see DURATION FORMAT)\. If not specified, the interval defaults to 1 second\.
.
.TP
\fB\-l\fR
Enables local loopback for published multicast datagrams\.
.
.TP
\fB\-o\fR \fIOFF\fR
Sets the offset from which all published payload sequence numbers will start\. The default is 0\.
.
.TP
\fB\-p\fR \fINUM\fR
Specify the UDP port of all created endpoints\. The default value is 22999\.
.
.TP
\fB\-s\fR \fISID\fR
Sets the session ID of each outgoing mbeat payload to \fISID\fR (see SESSION IDENTIFICATION)\. If not specified, a random value is generated\.
.
.TP
\fB\-t\fR \fITTL\fR
Sets the Time\-To\-Live property of each outgoing datagram to \fITTL\fR\. If not specified, the value defaults to 64\.
.
.TP
\fB\-v\fR
Enables more verbose logging\. Repeating this flag will turn on more detailed levels of logging messages: INFO, DEBUG, and TRACE\.
.
.SH "ENDPOINTS"
The positional arguments of the utility are endpoints: an ordered tuple consisting of local interface name, multicast group and the multicast port\. It is possible to specify up to 83886080 endpoints\.
.
.SH "SESSION IDENTIFICATION"
In order to support multiple simultaneous runs of the tool, the publisher can stamp the payload with a session ID \- a 64\-bit unsigned integer \- that identifies the set of outgoing packets\. Similarly the subscriber utility is able to filter out everything but a given session ID\.
.
.SH "DURATION FORMAT"
The time duration has to be specified by an unsigned integer, followed by a time unit\. An example of a valid duration is \fI1s\fR\. Supported units are: \fIns\fR, \fIus\fR, \fIms\fR, \fIs\fR, \fIm\fR, \fIh\fR, \fId\fR\. Zero duration is allowed, e\.g\. \fI0ms\fR\.
.
.SH "PAYLOAD FORMAT"
The format of the payload is binary\. All numeric fields are unsigned integers in network byte order, while the 64\-bit numbers are split into high and low 32\-bits, encoded in the network byte order\. The total payload size is 128 bytes\. All valid payloads must start with a magic number 0x6d626974, which stands for four ASCII letters "mbit"\. The current format version is 2\.
.
.P
Each payload contains the following fields in order:
.
.IP "\(bu" 4
magic value (4 bytes)
.
.IP "\(bu" 4
format version number (1 byte)
.
.IP "\(bu" 4
source Time\-To\-Live value (1 byte)
.
.IP "\(bu" 4
multicast port (2 bytes)
.
.IP "\(bu" 4
multicast group (4 bytes)
.
.IP "\(bu" 4
time of departure nanoseconds part (4 bytes)
.
.IP "\(bu" 4
time of departure UNIX timestamp (8 bytes)
.
.IP "\(bu" 4
session ID (8 bytes)
.
.IP "\(bu" 4
sequence interation counter (8 bytes)
.
.IP "\(bu" 4
sequence length (8 bytes)
.
.IP "\(bu" 4
publisher\'s interface name (16 bytes)
.
.IP "\(bu" 4
publisher\'s hostname (64 bytes)
.
.IP "" 0
.
.SH "RETURN VALUE"
The process returns \fI0\fR on success, \fI1\fR on failure\. Warnings and errors are printed to the standard error stream\.
.
.SH "SEE ALSO"
msub(8)
