.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MBEAT_SUB" "8" "August 2017" "" ""
.
.SH "NAME"
\fBmbeat_sub\fR \- multicast heartbeat subscriber
.
.SH "SYNOPSIS"
\fBmbeat_sub\fR [\fB\-b\fR \fIBSZ\fR] [\fB\-e\fR \fICNT\fR] [\fB\-h\fR] [\fB\-o\fR \fIOFF\fR] [\fB\-r\fR] [\fB\-s\fR \fISID\fR] [\fB\-t\fR \fIMS\fR] [\fB\-u\fR] \fIiface\fR=\fImaddr\fR:\fImport\fR [iface=maddr:mport \.\.\.]
.
.SH "DESCRIPTION"
The \fBmbeat_sub\fR utility subscribes to multicast UDP datagrams for a set of network endpoints\. It can be used in conjunction with the \fBmbeat_pub(8)\fR utility to test and debug network configurations\.
.
.SH "OPTIONS"
The utility accepts the following command\-line options:
.
.TP
\fB\-b\fR \fIBSZ\fR
Sets the socket receive buffer size to \fIBSZ\fR bytes\. If not specified, the value defaults to the Linux kernel default\.
.
.TP
\fB\-e\fR \fICNT\fR
If set, specifies the total number of datagrams to receive after which the process will exit with success\.
.
.TP
\fB\-h\fR
Prints the usage message\.
.
.TP
\fB\-o\fR \fIOFF\fR
Sets the sequence number offset, so that all mbeat payloads with sequence number lesser than \fIOFF\fR are ignored\. All subsequent sequence numbers are printed shifted by the \fIOFF\fR value\.
.
.TP
\fB\-r\fR
Enables the raw binary output instead of the default CSV\. See \fBOUTPUT FORMAT\fR\.
.
.TP
\fB\-s\fR \fISID\fR
Sets the session ID filter on incoming mbeat payloads, so that only those with session ID equal to \fISID\fR get printed out (see SESSION IDENTIFICATION)\. If not specified, all payloads are accepted\.
.
.TP
\fB\-t\fR \fIMS\fR
If set, the process will timeout and exit after \fIMS\fR milliseconds\.
.
.TP
\fB\-u\fR
Disables output buffering\.
.
.SH "ENDPOINTS"
The positional arguments of the utility are endpoints: an ordered tuple consisting of local interface name, multicast group and the multicast port\. It is possible to specify up to 2048 endpoints per subscriber\.
.
.SH "SESSION IDENTIFICATION"
In order to support multiple simultaneous runs of the tool, the publisher can stamp the payload with a session ID \- a 32\-bit unsigned integer \- that identifies the set of outgoing packets\. In return, the subscriber utility is able to exclusively listen to only certain session ID\.
.
.SH "PAYLOAD FORMAT"
The format of the payload is binary\. All numeric fields are unsigned integers in network byte order\. The total payload size is 108 bytes\.
.
.P
Each payload contains the following fields in order:
.
.IP "\(bu" 4
format version number (2 bytes)
.
.IP "\(bu" 4
multicast port (2 bytes)
.
.IP "\(bu" 4
multicast group (4 bytes)
.
.IP "\(bu" 4
sequence number (4 bytes)
.
.IP "\(bu" 4
session ID (4 bytes)
.
.IP "\(bu" 4
local interface name (16 bytes)
.
.IP "\(bu" 4
local host name (64 bytes)
.
.IP "\(bu" 4
time of departure UNIX timestamp (8 bytes)
.
.IP "\(bu" 4
time of departure nanoseconds part (4 bytes)
.
.IP "" 0
.
.SH "OUTPUT FORMAT \- CSV"
The default output format is ASCII\-encoded CSV file complaint with the RFC4180 standard\. The table has the following column headers:
.
.IP "\(bu" 4
SequenceNum
.
.IP "\(bu" 4
SessionID
.
.IP "\(bu" 4
MulticastAddr
.
.IP "\(bu" 4
MulticastPort
.
.IP "\(bu" 4
PubInterface
.
.IP "\(bu" 4
PubHostname
.
.IP "\(bu" 4
SubInterface
.
.IP "\(bu" 4
SubHostname
.
.IP "\(bu" 4
TimeOfDeparture
.
.IP "\(bu" 4
TimeOfArrival
.
.IP "" 0
.
.SH "OUTPUT FORMAT \- RAW BINARY"
The raw binary format re\-uses the exact structure of the payload, while appending 4 more fields:
.
.IP "\(bu" 4
interface name on the receivers end (16 bytes)
.
.IP "\(bu" 4
host name on the receivers end (64 bytes)
.
.IP "\(bu" 4
time of arrival UNIX timestamp (8 bytes)
.
.IP "\(bu" 4
time of arrival nanoseconds part (4 bytes)
.
.IP "" 0
.
.P
Unlike the CSV format, there is no header entry in raw binary\. Similar to the payload representation, data is outputted in the big\-endian byte order\.
.
.SH "RETURN VALUE"
The process returns \fI0\fR on success, \fI1\fR on failure\. Normal program output is printed on standard output and warnings and errors on standard error\.
.
.SH "SEE ALSO"
mbeat_pub(8)
